repos:
  - repo: local
    hooks:
      - id: lintcheck
        name: PHP Lint Checking
        entry: composer run-script lint
        language: system
        files: ^app/
        always_run: true

      - id: phpcsfixer
        name: PHP CS Fixer Validation
        entry: composer run-script phpcsfixer
        language: system
        files: ^app/
        always_run: true

      - id: phpstan
        name: PHPStan Validation
        entry: composer run-script phpstan
        language: system
        files: ^app/
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: end-of-file-fixer
        types: [php]
      - id: trailing-whitespace
        types: [php]
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
